#!/usr/bin/env bash

# This script selects a repo from the list of repos under
# $CODE_REPO_DIR and switches to that directory. Most
# Neovim plugins work relative to the CWD, so just setting
# it provides an experience similar to folders in VSCode.

if [ -z "$1" ]; then
  echo "Usage: $0 <repo-name>"
  exit 1
fi

if [ -z "$CODE_REPO_DIR" ]; then
  echo "CODE_REPO_DIR is not set. Please set it to the directory containing your repos."
  exit 1
fi

if [ ! -d "$CODE_REPO_DIR" ]; then
  echo "CODE_REPO_DIR does not exist. Please set it to a valid directory."
  exit 1
fi

REPO_NAME="$1"
REPO_PATH="$CODE_REPO_DIR/$REPO_NAME"
if [ ! -d "$REPO_PATH" ]; then
  echo "Repo $REPO_NAME does not exist in $CODE_REPO_DIR."
  exit 1
fi

# Check if the repo is a git repo
if [ ! -d ".git" ]; then
 echo "Repo $REPO_NAME is not a git repo."
 exit 1
fi

echo "Switched to repo $REPO_NAME in $REPO_PATH"
cd "$REPO_PATH" || exit 1
